# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Jason's Blog
subtitle: 分享交流大数据领域技术，包括但不限于Storm、Spark、Hadoop等流行分布式计算系统，Kafka、MetaQ等分布式消息系统，MongoDB、Cassandra等NoSQL，PostgreSQL、MySQL等RDBMS以及其它前沿技术
description: 分享交流大数据领域技术，包括但不限于Storm、Spark、Hadoop等流行分布式计算系统，Kafka、MetaQ等分布式消息系统，MongoDB、Cassandra等NoSQL，PostgreSQL、MySQL等RDBMS及其它前沿技术。微信公众号【大数据架构】
author: 郭俊 Jason
email: jason.guo.vip@gmail.com

## Sidebar profile image, only for next theme
avatar: //www.jasongj.com/img/WeChat_QR.png
#avatar: //cdn.jasongj.com/img/WeChat_QR.png


## language: en_US
##language: en_US
##language: zh-CN
language: zh-CN

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://www.jasongj.com
root: /
#permalink: :year/:month/:day/:title/
permalink: :title/
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
permalink_defaults:

# Directory
source_dir: source
public_dir: public

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: true # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
highlight:
  enable: true
  line_number: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Archives
## 2: Enable pagination
## 1: Disable pagination
## 0: Fully Disable
archive: 2
category: 2
tag: 2

# Server
## Hexo uses Connect as a server
## You can customize the logger format as defined in
## http://www.senchalabs.org/connect/logger.html
port: 4000
server_ip: 0.0.0.0
logger: false
logger_format: dev

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 100
pagination_dir: page


auto_detect: true


# Disqus
disqus_shortname:

# Extensions
Plugins:
 - hexo-generator-feed
 - hexo-generator-sitemap
 - hexo-generator-baidu-sitemap
 - hexo-generator-seo-friendly-sitemap
 - hexo-deployer-ftpsync
 - hexo-math
 - livereload

#Feed Atom
feed:
  type: atom
  path: atom.xml
  limit: 100

#sitemap
sitemap:
  path: /sitemap.xml
baidusitemap:
  path: /baidusitemap.xml


# Extensions
## Plugins: https://github.com/hexojs/hexo/wiki/Plugins
## Themes: https://github.com/hexojs/hexo/wiki/Themes
#theme: jacman
theme: next
exclude_generator:

# Deployment
## Docs: http://hexo.io/docs/deployment.html
#deploy 2.8.3
#deploy:
#- type: github
#  repository: git@github.com:habren/habren.github.io.git
#  branch: master
#- type: github
#  repository: git@gitcafe.com:jasongj/jasongj.git
#  branch: gitcafe-pages

# Deploy 3.1.1
deploy:
- type: git
  repo:
    github: git@github.com:habren/habren.github.io.git,master
    coding: git@git.coding.net:habren/habren.git,coding-pages
#- type: ftpsync
#  host: 120.24.239.7
#  user: syu2201940001
#  pass: gj418692341lh
#  remote: /htdocs
#  port: 21
#  ignore: ['.svn','logreport', '.git']
#  connections: 8
#  verbose: true

#deploy:
#  type: git
#  repo:
#    github: https://github.com/habren/habren.github.io.git,master
#    gitcafe: git@gitcafe.com:jasongj/jasongj.git,gitcafe-pages


  # Markdown
## https://github.com/chjj/marked
markdown:
  gfm: true
  pedantic: false
  sanitize: false
  tables: true
  breaks: true
  smartLists: true
  smartypants: true

# Stylus
stylus:
  compress: true

livereload:
  port: 35729

icp: 沪ICP备16005463号-1

## For next theme
since: 2015
social:
#  GitHub: https://github.com/habren
  Linkedin: https://www.linkedin.com/in/jasongj
  E-Mail: mailto:jason.guo.vip@gmail.com
  Weibo: http://weibo.com/habren

## Comments, for next
#duoshuo_shortname: habren

## Hotest articles
#duoshuo_hotartical: false

## Analytics, for next
baidu_analytics: 7dfdf667ba885e2b04d1c1cc561490f0
google_analytics: UA-58959834-1

## Google Webmaster tools, for next
google_site_verification: _lpnaoq9f4n68-jMrHuEIsB1kJO_6WMxvONibOMBdxM

## Swiftype search engine, for next
#swiftype_key: WSzRURyW4ED82aapXRTZ

## Friend links, for next
links_title: Links
links:
  发表在InfoQ上的文章: http://www.infoq.com/cn/author/%E9%83%AD%E4%BF%8A

## Share, for next
baidushare: false




